export const vehiculosRegistrados= [
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"A",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 {
    marca:"Chevrolet",
    modelo:"Aveo Family",
    anio:2019,
    placa:"GCA-3951",
    color: "Blanco",
    tipoVehiculo:"Carro",
    kmActual:158000,
    estado:"I",
 },
 


]